<a href="https://colab.research.google.com/github/Nancyrana1/Deep-Learning/blob/main/backpropogation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
df = pd.DataFrame([[8,8,4],[6,10,6],[5,12,7]], columns=['cgpa','profile_score','lpa'])
df

,cgpa,profile_score,lpa
0,8,8,4
1,6,10,6
2,5,12,7


In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   cgpa           3 non-null      int64
 1   profile_score  3 non-null      int64
 2   lpa            3 non-null      int64
dtypes: int64(3)
memory usage: 204.0 bytes


In [ ]:
import tensorflow
from tensorflow import keras
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense, Flatten

In [ ]:
model = Sequential()
model.add(Dense(2,activation='linear',input_dim=2))
model.add(Dense(1,activation='linear'))

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [ ]:
model.summary()

Model: "sequential_4"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_5 (Dense)                 │ (None, 2)              │             6 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_6 (Dense)                 │ (None, 1)              │             3 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 9 (36.00 B)

 Trainable params: 9 (36.00 B)

 Non-trainable params: 0 (0.00 B)

In [ ]:
model.get_weights()

In [ ]:
new_wts = [np.array([[0.1,0.1],
                     [0.1,0.1]],dtype=np.float32),
           np.array([0.,0.],dtype=np.float32),
           np.array([[0.1],
                     [0.1]],dtype=np.float32),
           np.array([0.],dtype=np.float32)]

In [ ]:
model.set_weights(new_wts)

In [ ]:
model.get_weights()

[array([[ 0.99558365, -0.698108  ],
        [ 0.23206067, -0.5725685 ]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[1.0270823 ],
        [0.59246933]], dtype=float32),
 array([0.], dtype=float32)]

In [ ]:
optimizer = keras.optimizers.Adam(learning_rate=0.001)
model.compile(loss='mean_squared_error',optimizer=optimizer)

In [ ]:
model.fit(df.iloc[:,0:-1].values,df['lpa'].values,epochs=1000,verbose=1,batch_size=1)

Epoch 1/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 29.9872 
Epoch 2/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 29.7322
Epoch 3/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 29.4943
Epoch 4/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 29.2074
Epoch 5/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 28.9755
Epoch 6/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 28.6799
Epoch 7/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 28.4433
Epoch 8/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 28.1323
Epoch 9/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 27.8479
Epoch 10/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 27.5860
Epoch 11/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 27.2829
Epoch 12/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 26.9469
Epoch 13/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 26.6374
Epoch 14/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 26.3170
Epoch 15/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - lo

In [ ]:
model.get_weights()

[array([[-0.03091613, -0.03091613],
        [ 0.5923807 ,  0.5923807 ]], dtype=float32),
 array([0.21352817, 0.21352817], dtype=float32),
 array([[0.46560726],
        [0.46560726]], dtype=float32),
 array([0.15698887], dtype=float32)]