<a href="https://colab.research.google.com/github/Nancyrana1/Deep-Learning/blob/main/Pytorch_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch

print(torch.__version__)

2.11.0+cu128


In [ ]:
if torch.cuda.is_available():
  print("gpu available")
  print("\n current device:" ,torch.cuda.current_device())
  print("\n Using GPU " ,torch.cuda.get_device_name(0))
else:
  print("not available")

gpu available

 current device: 0

 Using GPU  Tesla T4


CREATING TENSORS

In [ ]:
scalar_tensor = torch.tensor(7)
print(scalar_tensor)

tensor(7)


In [ ]:
a=torch.empty(2,3)
print(a)
print(type(a))

tensor([[2.5835e-31, 0.0000e+00, 1.8708e-31],
        [0.0000e+00, 4.4842e-44, 0.0000e+00]])
<class 'torch.Tensor'>


In [ ]:
b=torch.zeros(2,3)
print(b)



tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [ ]:
c=torch.ones(2,3)
print(c)

tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [ ]:
d = torch.rand(2,3)
print(d)

tensor([[0.9641, 0.2490, 0.1174],
        [0.5926, 0.5136, 0.5753]])


FULLFIL REPRODUCIBILITY

In [ ]:
torch.manual_seed(30)
torch.rand(2,3)

tensor([[0.9007, 0.7464, 0.4716],
        [0.8738, 0.7403, 0.7840]])

In [ ]:
e=torch.tensor([[1,2,3],[4,5,6]])
print(e)

tensor([[1, 2, 3],
        [4, 5, 6]])


In [ ]:
print("using arange - >",torch.arange(0,10))

using arange - > tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [ ]:
print("using linspace - >", torch.linspace(0,10,10))

using linspace - > tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])


IDENTITY MATRIX USING EYE

In [ ]:
print("using eye - >", torch.eye(3))

using eye - > tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


In [ ]:
a.shape

torch.Size([2, 3])

In [ ]:
d.shape

torch.Size([2, 3])

In [ ]:
e.shape

torch.Size([2, 3])

In [ ]:
torch.empty_like(e)

tensor([[137447435713920,       215048464,               0],
        [              0,               0,               0]])

tensor mathematical operations

In [ ]:
x = torch.rand(2,3)
x

tensor([[0.8946, 0.6238, 0.4276],
        [0.8421, 0.7454, 0.6181]])

In [ ]:
print("\n additon ->", x+2)
print("\n subtraction ->", x-2)
print("\n multiplication ->", x*2)
print("\n division ->", x/2)



 additon -> tensor([[2.8946, 2.6238, 2.4276],
        [2.8421, 2.7454, 2.6181]])

 subtraction -> tensor([[-1.1054, -1.3762, -1.5724],
        [-1.1579, -1.2546, -1.3819]])

 multiplication -> tensor([[1.7892, 1.2477, 0.8552],
        [1.6842, 1.4909, 1.2363]])

 division -> tensor([[0.4473, 0.3119, 0.2138],
        [0.4210, 0.3727, 0.3091]])


In [ ]:
b = torch.rand(2,3)
b

tensor([[0.8883, 0.4127, 0.1748],
        [0.3426, 0.9377, 0.0413]])

In [ ]:
print("\n additon ->", x+b)
print("\n subtraction ->", x-b)
print("\n multiplication ->", x*b)
print("\n division ->", x/b)
print("\n power ->", a**b)


 additon -> tensor([[1.7828, 1.0366, 0.6024],
        [1.1847, 1.6832, 0.6594]])

 subtraction -> tensor([[ 0.0063,  0.2111,  0.2528],
        [ 0.4994, -0.1923,  0.5768]])

 multiplication -> tensor([[0.7946, 0.2575, 0.0748],
        [0.2885, 0.6990, 0.0255]])

 division -> tensor([[ 1.0071,  1.5114,  2.4459],
        [ 2.4576,  0.7949, 14.9665]])

 power -> tensor([[6.7657e-28, 0.0000e+00, 4.2474e-06],
        [0.0000e+00, 2.2432e-41, 0.0000e+00]])


In [ ]:
c = torch.tensor([-1,-2,3,-5])
print(torch.abs(c))

tensor([1, 2, 3, 5])


In [ ]:
print(torch.neg(c))

tensor([ 1,  2, -3,  5])


In [ ]:
d = torch.tensor([1.9,2.4,9,7.3])
print(torch.round(d))

tensor([2., 2., 9., 7.])


In [ ]:
print(torch.ceil(d))

tensor([2., 3., 9., 8.])


In [ ]:
print(torch.floor(d))

tensor([1., 2., 9., 7.])


In [ ]:
print(torch.clamp(d, min=2,max=3))

tensor([2.0000, 2.4000, 3.0000, 3.0000])


Reduction Operation

In [ ]:
e = torch.randint(size=(2,3),low=0,high=10)
print(e)

tensor([[5, 9, 5],
        [8, 0, 8]])


In [ ]:
torch.sum(e)

tensor(35)

In [ ]:
# alongside column
torch.sum(e, dim=0)

tensor([13,  9, 13])

In [ ]:
# alongside row

torch.sum(e, dim = 1)

tensor([19, 16])

In [ ]:
e = torch.randint(size=(2,3),low=0,high=10,dtype=torch.float32)

In [ ]:
# mean operates with the floating numbers
torch.mean(e)

tensor(3.6667)

In [ ]:
torch.median(e)

tensor(2.)

In [ ]:
torch.max(e)


tensor(8.)

In [ ]:
torch.min(e)


tensor(2.)

In [ ]:
torch.std(e)


tensor(2.3381)

In [ ]:
torch.argmax(e)

tensor(5)

In [ ]:
torch.argmin(e)

tensor(0)

tensor(0)

MATRIX OPERATIONS

In [ ]:
x = torch.randint(size = (2,3), low=0,high=10)
y = torch.randint(size = (3,4), low=0,high=10)

In [ ]:
print(x)
print(y)

tensor([[5, 0, 9],
        [0, 4, 3]])
tensor([[9, 3, 8, 1],
        [6, 1, 3, 0],
        [5, 8, 3, 0]])


In [ ]:
torch.matmul(x,y)

tensor([[90, 87, 67,  5],
        [39, 28, 21,  0]])

In [ ]:
vec1 = torch.tensor([1,2])
vec2 = torch.tensor([3,4])

In [ ]:
print(torch.dot(vec1,vec2))

tensor(11)


In [ ]:
torch.transpose(e,0,1)

tensor([[2., 4.],
        [2., 4.],
        [2., 8.]])

SPECIAL FUNCTIONS

In [ ]:
k = torch.randint(size=(2,3),low=0,high=10, dtype =torch.float32)
k

tensor([[3., 9., 7.],
        [5., 3., 3.]])

In [ ]:
torch.log(k)

tensor([[1.0986, 2.1972, 1.9459],
        [1.6094, 1.0986, 1.0986]])

In [ ]:
torch.exp(k)

tensor([[  20.0855, 8103.0840, 1096.6332],
        [ 148.4132,   20.0855,   20.0855]])

In [ ]:
torch.sqrt(k)

tensor([[1.7321, 3.0000, 2.6458],
        [2.2361, 1.7321, 1.7321]])

In [ ]:
torch.sigmoid(k)

tensor([[0.9526, 0.9999, 0.9991],
        [0.9933, 0.9526, 0.9526]])

In [ ]:
torch.softmax(k,dim=0)

tensor([[0.1192, 0.9975, 0.9820],
        [0.8808, 0.0025, 0.0180]])

In [ ]:
torch.relu(k)

tensor([[3., 9., 7.],
        [5., 3., 3.]])

INPLACE OPERATIONS

In [ ]:
m =torch.rand(2,3)
n =torch.rand(2,3)

In [ ]:
print(m)
print("\n")
print(n)

tensor([[0.8220, 0.2750, 0.4322],
        [0.8771, 0.9301, 0.7586]])


tensor([[0.6401, 0.9802, 0.6769],
        [0.7497, 0.6752, 0.6840]])


In [ ]:
m.add_(n)

tensor([[1.4621, 1.2552, 1.1091],
        [1.6268, 1.6054, 1.4426]])

In [ ]:
m.relu_()

tensor([[1.4621, 1.2552, 1.1091],
        [1.6268, 1.6054, 1.4426]])

COPY A TENSOR - >CLONE()

In [ ]:
p = m.clone()

COMPARISON CODE OF CPU AND GPU

In [ ]:
import time

size=10000

a = torch.randn(size,size)
b = torch.randn(size,size)

start_time = time.time()
matrix_multi_cpu = torch.matmul(a,b)
print("CPU time - > ",time.time() - start_time)

a1 = a.to('cuda')
b1 = b.to('cuda')

start_time = time.time()
matrix_multi_gpu = torch.matmul(a1,b1)
print("GPU time - > ",time.time() - start_time)


CPU time - >  17.004087924957275
GPU time - >  0.00031304359436035156


MOVING TENSORS FROM PYTORCH TO NUMPY ARRAYS

In [ ]:
import numpy as np
a = torch.tensor([1,2,3])
a

tensor([1, 2, 3])

In [ ]:
b = a.numpy()
print(type(b))

<class 'numpy.ndarray'>


In [ ]:
c=torch.from_numpy(b)
c

tensor([1, 2, 3])

In [ ]:
print(type(b))

<class 'numpy.ndarray'>
